sudo: false
language: python
dist: xenial
python:
  - 3.8
env:
  - IMP_BRANCH=develop
  - IMP_BRANCH=master
install:
  - source support/setup_travis.sh $HOME/miniconda $IMP_BRANCH $TRAVIS_PYTHON_VERSION
  - python -V
script:
  - mkdir build
  - cd build
  - cmake .. -DIMP_DIR=${CONDA_PREFIX}/lib/cmake/IMP
  - make
  - ./simple
