.PHONY: clean cleaner

all:
	python3 ../support/tutorial_tools/notebook/process_notebook.py using_cpp

clean:
	rm -f using_cpp.py using_cpp.md Doxyfile
	rm -rf html

cleaner:
	rm -f using_cpp.ipynb using_cpp.py using_cpp.md Doxyfile
	rm -rf html
